version: '{build}'
os: Visual Studio 2019

environment:
  SBT_OPTS: -Dfile.encoding=UTF8
  JAVA_OPTS: -Dfile.encoding=UTF8
  matrix:
      - JAVA_HOME: C:\Program Files\Java\jdk10
      - JAVA_HOME: C:\Program Files\Java\jdk11
      - JAVA_HOME: C:\Program Files\Java\jdk12

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://piccolo.link/sbt-1.3.8.zip',
          'C:\sbt-bin-1.3.8.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin-1.3.8.zip", "C:\sbt")
      }
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-Xmx4g

build_script:
  - echo

test_script:
  - sbt ^test ^scripted
  - ps: |
      Get-ChildItem -Path examples -Directory -ErrorAction 'Stop' |
      foreach {
          cd $_.FullName; sbt test
      }

cache:
  - 'C:\sbt -> appveyor.yml'
  - '%USERPROFILE%\.ivy2 -> appveyor.yml'
